// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsYj-C3Nc6fC3wJr8oZYnQR6StrTxKtac',
    appId: '1:1033030216210:web:695a290dc1b276795386cb',
    messagingSenderId: '1033030216210',
    projectId: 'ovu-healthcare-app',
    authDomain: 'ovu-healthcare-app.firebaseapp.com',
    storageBucket: 'ovu-healthcare-app.appspot.com',
    measurementId: 'G-8GWL4FCGZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClBOhF2vUTp2WIIFDPhuY0pF0jpsnUQ34',
    appId: '1:1033030216210:android:0f5da1f4e2a883265386cb',
    messagingSenderId: '1033030216210',
    projectId: 'ovu-healthcare-app',
    storageBucket: 'ovu-healthcare-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzJv608_HGrJFL6jNVvW6hqBAzzabUINY',
    appId: '1:1033030216210:ios:a598a7af476b21ef5386cb',
    messagingSenderId: '1033030216210',
    projectId: 'ovu-healthcare-app',
    storageBucket: 'ovu-healthcare-app.appspot.com',
    iosBundleId: 'com.example.ovuHealthcareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzJv608_HGrJFL6jNVvW6hqBAzzabUINY',
    appId: '1:1033030216210:ios:6d105f857cfa96d15386cb',
    messagingSenderId: '1033030216210',
    projectId: 'ovu-healthcare-app',
    storageBucket: 'ovu-healthcare-app.appspot.com',
    iosBundleId: 'com.example.ovuHealthcareApp.RunnerTests',
  );
}
